## Review template file for Tumbleweed test runs on O3

Instance = "https://openqa.opensuse.org"                        # openQA instance to query
RabbitMQ = "amqps://opensuse:opensuse@rabbit.opensuse.org"      # RabbitMQ instance to query
RabbitMQTopic = "opensuse.openqa.job.done"                      # RabbitMQ topic to query
HideStatus = ["scheduled", "passed", "softfailed", "cancelled", "skipped", "running", "uploading", "parallel_failed", "reviewed", "user_cancelled"]  # Hide jobs in defined states
RefreshInterval = 60                                            # Refresh from API once every minute
MaxJobs = 20                                                    # Max. job per group to display
GroupBy = "groups"                                              # Group by defined groups ("none" or "groups")
DefaultParams = { distri="opensuse", version = "Tumbleweed" }   # Set of default parameters
RequestJobLimit = 100                                           # Query up to 100 jobs per http request

## Define job groups

[[Groups]]
Name = "openSUSE Tumbleweed DVD"
Params = { flavor = "DVD" }
MaxLifetime = 86400

[[Groups]]
Name = "openSUSE Tumbleweed Network"
Params = { flavor = "NET" }
MaxLifetime = 86400

[[Groups]]
Name = "openSUSE Tumbleweed JeOS"
Params = { flavor = "JeOS-for-kvm-and-xen" }
MaxLifetime = 86400

[[Groups]]
Name = "openSUSE Tumbleweed Gnome-Live"
Params = { flavor = "GNOME-Live" }
MaxLifetime = 86400
[[Groups]]
Name = "openSUSE Tumbleweed KDE-Live"
Params = { flavor = "KDE-Live" }
MaxLifetime = 86400
