## Review template file for Tumbleweed BCI test runs on openqa.opensuse.org

Instance = "https://openqa.opensuse.org"                        # openQA instance to query
RabbitMQ = "amqps://opensuse:opensuse@rabbit.opensuse.org"      # RabbitMQ instance to query
RabbitMQTopic = "opensuse.openqa.job.done"                      # RabbitMQ topic to query
HideStatus = ["scheduled", "passed", "softfailed", "cancelled", "skipped", "running", "uploading", "parallel_failed", "reviewed", "user_cancelled"]  # Hide jobs in defined states
RefreshInterval = 60                                            # Refresh from API once every minute
MaxJobs = 100                                                   # Max. job per group to display
GroupBy = "groups"                                              # Group by defined groups ("none" or "groups")
DefaultParams = { distri="opensuse", version = "Tumbleweed" }   # Set of default parameters
RequestJobLimit = 100                                           # Query up to 100 jobs per http request

## Define job groups

[[Groups]]
Name = "openSUSE Tumbleweed BCI x86_64"
Params = { flavor = "BCI", groupid = "1" }
MaxLifetime = 86400

[[Groups]]
Name = "openSUSE Tumbleweed BCI aarch64"
Params = { flavor = "BCI", groupid = "3" }
MaxLifetime = 86400
