## Review template file for PublicCloud test runs on OSD

Instance = "https://openqa.suse.de"              # openQA instance to query
RabbitMQ = "amqps://suse:suse@rabbit.suse.de"    # RabbitMQ instance to query
RabbitMQTopic = "suse.openqa.job.done"           # RabbitMQ topic to query
HideStatus = ["scheduled", "passed", "softfailed", "cancelled", "skipped", "running", "uploading", "parallel_failed", "reviewed" ]           # Hide scheduled and passed jobs
Notify = false                                   # No notifications by default
RefreshInterval = 60                             # Refresh from API once every minute
MaxJobs = 20                                     # Max. job per group to display
GroupBy = "groups"                               # Group by defined groups ("none" or "groups")
DefaultParams = { distri = "sle" }               # Set of default parameters

# Incidents

[[Groups]]
Name = "Public Cloud Incident test runs"
Params = { groupid = "430" }
MaxLifetime = 86400

# Define publiccloud aggregate runs based on their Flavor

[[Groups]]
Name = "AZURE-Basic-Updates"
Params = { flavor = "AZURE-Basic-Updates", build = "%yesterday%-1" }
[[Groups]]
Name = "AZURE-Basic-gen2-Updates"
Params = { flavor = "AZURE-Basic-gen2-Updates", build = "%yesterday%-1" }
[[Groups]]
Name = "AZURE-Standard-Updates"
Params = { flavor = "AZURE-Standard-Updates", build = "%yesterday%-1" }
[[Groups]]
Name = "AZURE-Standard-gen2-Updates"
Params = { flavor = "AZURE-Standard-gen2-Updates", build = "%yesterday%-1" }
[[Groups]]
Name = "AZURE-BYOS-Updates"
Params = { flavor = "AZURE-BYOS-Updates", build = "%yesterday%-1" }
[[Groups]]
Name = "AZURE-BYOS-gen2-Updates"
Params = { flavor = "AZURE-BYOS-gen2-Updates", build = "%yesterday%-1" }
[[Groups]]
Name = "EC2-BYOS-Updates"
Params = { flavor = "EC2-BYOS-Updates", build = "%yesterday%-1" }
[[Groups]]
Name = "EC2-BYOS-ARM-Updates"
Params = { flavor = "EC2-BYOS-ARM-Updates", build = "%yesterday%-1" }
[[Groups]]
Name = "EC2-Updates"
Params = { flavor = "EC2-Updates", build = "%yesterday%-1" }
[[Groups]]
Name = "EC2-ARM-Updates"
Params = { flavor = "EC2-ARM-Updates", build = "%yesterday%-1" }
[[Groups]]
Name = "GCE-Updates"
Params = { flavor = "GCE-Updates", build = "%yesterday%-1" }
[[Groups]]
Name = "GCE-BYOS-Updates"
Params = { flavor = "GCE-BYOS-Updates", build = "%yesterday%-1" }

# Latest

[[Groups]]
Name = "Azure Latest"
Params = { groupid = "219", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "GCE Latest"
Params = { groupid = "275", build = "" }
MaxLifetime = 86400

[[Groups]]
Name = "EC2 Latest"
Params = { groupid = "274", build = "" }
MaxLifetime = 86400

# Create HDD

[[Groups]]
Name = "Create HDD"
Params = { groupid = "276", build = "" }
MaxLifetime = 86400

